.pip_configure: &pip_configure |
  # Since the PIP servers stopped supporting of TLS < 1.2, we cannot use socks proxy to conneсt them
  # In common case we can use 'unset ALL_PROXY' if we don't want to play with NO_PROXY
  env | grep -i proxy
  NO_PROXY=".cn,${NO_PROXY}"
  export NO_PROXY
  env | grep -i proxy
  mkdir -p ~/.pip
  echo "[global]" > ~/.pip/pip.conf
  echo "index-url = https://pypi.mirrors.ustc.edu.cn/simple" >> ~/.pip/pip.conf

before_script:
  # Disable configuration with chinese mirrors, because Brno runner is used
  # - *pip_configure
  - pip install tox==3.0.0 
  
cache:
  paths:
   - .tox

stages:
  - check
  - test

test:py27:
  image: python:2.7
  stage: test
  tags:
    - build
  script:
   - tox -e py27

test:py35:
  image: python:3.5
  stage: test
  tags:
    - build
  script:
   - tox -e py35

test:py36:
  image: python:3.6
  stage: test
  tags:
    - build
  script:
   - tox -e py36

test:py37:
  image: python:3.7
  stage: test
  tags:
    - build
  script:
   - tox -e py37

lint:
  image: python:3.7
  stage: check
  tags:
    - build
  artifacts:
    when: on_failure
    paths:
      - flake8_output.txt
      - bandit_output.txt
    expire_in: 1 week
  before_script:
    - pip install bandit==1.5.1 flake8
  script:
    - bandit -r -f txt -o bandit_output.txt .
    - flake8 --config=.flake8 --output-file=flake8_output.txt --tee 
    