before_script:
  - pip install tox==3.0.0 
  
cache:
  paths:
   - .tox

stages:
- test

test:py27:
  image: python:2.7
  stage: test
  tags:
    - build
  script:
   - tox -e py27

test:py34:
  image: python:3.4
  stage: test
  tags:
    - build
  script:
   - tox -e py34

test:py35:
  image: python:3.5
  stage: test
  tags:
    - build
  script:
   - tox -e py35

test:py36:
  image: python:3.6
  stage: test
  tags:
    - build
  script:
   - tox -e py36

test:py37:
  image: python:3.7
  stage: test
  tags:
    - build
  script:
   - tox -e py37