cache:
  paths:
    - .tox

stages:
  - check
  - test
  - deploy

lint:
  image: python:3.8-buster
  stage: check
  tags:
    - lint
    - internet
  artifacts:
    when: on_failure
    paths:
      - flake8_output.txt
      - bandit_output.txt
    expire_in: 1 week
  before_script:
    - pip install bandit flake8
  script:
    - bandit --exclude="./tests,./integration_tests,./.tox,./.git" -r -f txt -o bandit_output.txt .
    - flake8 --config=.flake8 --output-file=flake8_output.txt --tee

test:
  image: quay.io/python-devs/ci-image:master
  stage: test
  tags:
    - test
    - internet
  script:
    - tox
  artifacts:
    reports:
      cobertura: coverage.xml

publish_on_pypi:
  image: python:3.8-slim-buster
  stage: deploy
  tags:
    - internet
  variables:
    TWINE_NON_INTERACTIVE: "true"
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: ${PYPI_TOKEN}
  before_script:
    - apt update && apt install curl jq -y
    - pip install twine
  script:
    - ./publish.sh
  only:
    refs:
      - master

test:py27int:
  image: python:2.7-slim-buster
  stage: test
  tags:
    - test
    - internet
  only:
    refs:
      - master
      - schedules
  before_script:
    - apt-get update && apt-get install -y -q libusb-1.0 cmake git ninja-build
    - git clone https://github.com/espressif/esp-idf.git
    - cd ./esp-idf/
    - ./install.sh
    - . ./export.sh
    - git submodule update --init --recursive
    - cd ..
    - pip install $CI_PROJECT_DIR pytest
  script:
    - py.test -s -c pytest_integration.ini

test:py38int:
  image: python:3.8-slim-buster
  stage: test
  tags:
    - test
    - internet
  only:
    refs:
      - master
      - schedules
  before_script:
    - apt-get update && apt-get install -y -q libusb-1.0 cmake git ninja-build
    - git clone https://github.com/espressif/esp-idf.git
    - cd ./esp-idf/
    - ./install.sh
    - . ./export.sh
    - git submodule update --init --recursive
    - cd ..
    - pip install $CI_PROJECT_DIR pytest
  script:
    - py.test -s -c pytest_integration.ini

