cache:
  paths:
    - .tox

stages:
  - check
  - test
  - deploy

lint:
  image: python:3.8-slim-buster
  stage: check
  tags:
    - lint
    - internet
  artifacts:
    when: on_failure
    paths:
      - flake8_output.txt
      - bandit_output.txt
    expire_in: 1 week
  before_script:
    - pip install bandit flake8
  script:
    - bandit --exclude="./tests,./.tox,./.git" -r -f txt -o bandit_output.txt .
    - flake8 --config=.flake8 --output-file=flake8_output.txt --tee

test:
  image: quay.io/python-devs/ci-image:master
  stage: test
  tags:
    - test
    - internet
  script:
    - tox

publish_on_pypi:
  image: python:3.8-slim-buster
  stage: deploy
  tags:
    - internet
  variables:
    TWINE_NON_INTERACTIVE: "true"
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: ${PYPI_TOKEN}
  before_script:
    - apt update && apt install curl jq -y
    - pip install twine
  script:
    - ./publish.sh
  only:
    refs:
      - master
