cache:
  paths:
    - .tox

stages:
  - check
  - test

lint:
  image: python:3.7
  stage: check
  tags:
    - lint
    - internet
  artifacts:
    when: on_failure
    paths:
      - flake8_output.txt
      - bandit_output.txt
    expire_in: 1 week
  before_script:
    - pip install bandit flake8
  script:
    - bandit -r -f txt -o bandit_output.txt .
    - flake8 --config=.flake8 --output-file=flake8_output.txt --tee

.before_test: &before_test |
  pip install tox
  # This is workaround to allow access for git 
  git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.espressif.cn:6688/idf/component_management_tools.git /test/component_management_tools

test:py27:
  image: python:2.7
  stage: test
  tags:
    - test
    - internet
  script:
    - *before_test
    - tox -e py27

test:py35:
  image: python:3.5
  stage: test
  tags:
    - test
    - internet
  script:
    - *before_test
    - tox -e py35

test:py36:
  image: python:3.6
  stage: test
  tags:
    - test
    - internet
  script:
    - *before_test
    - tox -e py36

test:py37:
  image: python:3.7
  stage: test
  tags:
    - test
    - internet
  script:
    - *before_test
    - tox -e py37

test:py38:
  image: python:3.8
  stage: test
  tags:
    - test
    - internet
  script:
    - *before_test
    - tox -e py38
